### PR TITLE
newTab react options configured

### PR DESCRIPTION
**Pull request by madaley1**
Configured new tab options for iSearch

### CODE REVIEW

**Comment by jkcox** [comment]
I would update your new tab property to use true/false instead of "newTab"

`"newTab":"newtab"` to `"newTab":"false"`

iSearchCardView and others that are checking for true/false will be all set, then update the files like iSearchDirectoryWrapper that are checking for `if(config.newTab == undefined) { config.newTab = "newtab"; }` change that to true/false

**Comment by jkcox** [comment]
@madaley1  Well I wasn't paying close attention when I gave you feedback, my bad - 1 more quick update

`"false"` needs to be `false`

string vs boolean, we need the boolean for the logic check

I was curious what would happen comparing a string w/ boolean - 

`var myBool = Boolean("false");  // == true

var myBool = !!"false";  // == true`

Seems like any string which isn't the empty string will evaluate to true by using them in Javascript.

**Comment by jkcox** [comment]
@madaley1  Well I wasn't paying close attention when I gave you feedback, my bad - 1 more quick update

`"false"` needs to be `false`

string vs boolean, we need the boolean for the logic check

I was curious what would happen comparing a string w/ boolean - 

`var myBool = Boolean("false");  // == true

var myBool = !!"false";  // == true`

Seems like any string which isn't the empty string will evaluate to true by using them in Javascript.

**Comment by madaley1** [comment]
Closing this as it's almost a couple years old and probably not relevant anymore!

**Pull request closed without merging**
